### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by Simon-Jarke** [VerenaSchmidt11/LegoExperiment#1]
Hey, I'm opening an issue here, hoping you're the same @VerenaSchmidt11 from the Bosch XDK community. Are you?

I saw your entry in the forum: https://community.developer.bosch.com/t5/Technical-Support-Read-only/Problems-with-XDK-and-Azure-Plug-and-Play/m-p/47469#M1008. I have exactly the same problem. Have you been able to solve it somehow?

Sorry for the stalking!

Regards,
Simon

**Comment by VerenaSchmidt11** [comment]
Hi Simon, 
I understand that you also have problems with the WLAN connection in order to get Azure Plug&Play running with the Bosch XDK.  I got the following solution and it worked for me:

 

The WiFi Chip has an old Firmware Version - Update the firmware according to Developer Portal (bosch.com)

looking at «Wi-Fi Module upgrade» 

Afterwards you need the following output - which means that the firmware is 1.0.3.37

INFO | XDK DEVICE 1: PHY 1.0.3.37 

Hopefully that helps.

Yours, Verena

**Comment by Simon-Jarke** [comment]
Hi Verena,

awesome, your suggestion has indeed helped and solved the problem! Thank you very much for the help! :-)

Simon
